name: Docker Image CI
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t '${{secrets.DOCKER_LOGIN}}'/ctse-lab-12:'${{github.sha}}' .

      - name: docker login
        run: docker login --username '${{secrets.DOCKER_LOGIN}}' --password '${{secrets.DOCKER_PASSWORD}}'

      - name: push docker image
        run: docker push '${{secrets.DOCKER_LOGIN}}'/ctse-lab-12:'${{github.sha}}'
      
    # - name: Update config files in k8s
    #   run: sed -i.bak 's/{{tag}}/${{ github.sha }}/g' k8s/deploy.yaml  && rm k8s/*.bak
    # - uses: actions-hub/kubectl@master
    #   env:
    #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    #   with:
    #     args: apply -f ./k8s